DSS_PARAMS = DSSComps(EPOCHS_FILT,EEG_PARAMS,SAVE_PARAMS);

POWER = SimSSVEP(EPOCHS_RT,DSS_PARAMS,EEG_PARAMS);

DSS_PARAMS = CdfEstimate(POWER,DSS_PARAMS,RT_PARAMS,EEG_PARAMS,SAVE_PARAMS);
save([savepath 'DSS_PARAMS'],'DSS_PARAMS','EEG_PARAMS','RT_PARAMS');