GPFA_PARAMS = GPFAComps(EPOCHS_FILT,EEG_PARAMS,RT_PARAMS,SAVE_PARAMS);

POWER = SimSSVEP(EPOCHS_RT,GPFA_PARAMS,EEG_PARAMS);

GPFA_PARAMS = CdfEstimate(POWER,GPFA_PARAMS,RT_PARAMS,EEG_PARAMS,SAVE_PARAMS);
save([savepath 'GPFA_PARAMS'],'GPFA_PARAMS','EEG_PARAMS','RT_PARAMS');